# Generated by Django 4.2.4 on 2023-08-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_payments_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='user',
            field=models.CharField(max_length=250, verbose_name='Пользователь'),
        ),
    ]
